FROM gradle:7-jdk11 as base
COPY ./app /base
WORKDIR /base
RUN gradle build

FROM openjdk:11.0.13-jdk-slim
WORKDIR /app
COPY --from=base /base/build/libs/base.jar /app
ENV SERVER_PORT=8080
CMD ["java", "-jar", "/app/base.jar", "--server.port", "${SERVER_PORT}"]